version: '3.7'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: myapp-server
    # container_name: myapp-node-server
    #command: npm start
    volumes:
      - ./server/:/usr/src/app
      #- /usr/src/app/node_modules
    ports:
      - "5050:5050"
    depends_on:
      - mongo
    # env_file: ./server/.env
    environment:
      - DB_HOST=mongo
      - DB_PORT=27017
      - DB_NAME=app
      - DB_USER=root
      - DB_PASS=app
    # environment:
    #   - NODE_ENV=development
    networks:
      - app-network
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=app
    volumes:
      - data-volume:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    # image: myapp-client
    #container_name: myapp-react-client
    #command: npm start
    volumes:
      - ./client/:/usr/src/app
      #- /usr/app/node_modules
    depends_on:
      - server
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
    app-network:
        driver: bridge

volumes:
    data-volume:
    node_modules:
    web-root:
      driver: local