services:
  web: 
    build:
      context: ./mysite
      target: builder
    ports: 
      - '8000:8000'
    environment:
      MARIADB_USER: root
      MARIADB_ROOT_PASSWORD: example
      MARIADB_HOST: db
      MARIADB_PORT: 3306
      MARIADB_DATABASE: djangodemo
  db:
    image: mariadb:10.11
    # ports:
    #   - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_DATABASE: djangodemo

